reporting: "off"
startuppopupversion: 1
gui:
  theme:
    lightTheme: true
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - blue
    selectedLineBgColor:
      - default